config/routes.rb
Found::Application.routes.draw do
  resources :cheeses
  root :to => 'cheeses#index'

end

app/models/cheese.rb
class Cheese < ActiveRecord::Base
  attr_accessible :color, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cheeses_controller.rb
class CheesesController < ApplicationController
  # GET /cheeses
  # GET /cheeses.json
  def index
    @cheeses = Cheese.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cheeses }
    end
  end

  # GET /cheeses/1
  # GET /cheeses/1.json
  def show
    @cheese = Cheese.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cheese }
    end
  end

  # GET /cheeses/new
  # GET /cheeses/new.json
  def new
    @cheese = Cheese.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cheese }
    end
  end

  # GET /cheeses/1/edit
  def edit
    @cheese = Cheese.find(params[:id])
  end

  # POST /cheeses
  # POST /cheeses.json
  def create
    @cheese = Cheese.new(params[:cheese])

    respond_to do |format|
      if @cheese.save
        format.html { redirect_to @cheese, notice: 'Cheese was successfully created.' }
        format.json { render json: @cheese, status: :created, location: @cheese }
      else
        format.html { render action: "new" }
        format.json { render json: @cheese.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cheeses/1
  # PUT /cheeses/1.json
  def update
    @cheese = Cheese.find(params[:id])

    respond_to do |format|
      if @cheese.update_attributes(params[:cheese])
        format.html { redirect_to @cheese, notice: 'Cheese was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cheese.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cheeses/1
  # DELETE /cheeses/1.json
  def destroy
    @cheese = Cheese.find(params[:id])
    @cheese.destroy

    respond_to do |format|
      format.html { redirect_to cheeses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheeses_helper.rb
module CheesesHelper
end

app/views/cheeses/_form.html.erb
<%= form_for(@cheese) do |f| %>
  <% if @cheese.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cheese.errors.count, "error") %> prohibited this cheese from being saved:</h2>

      <ul>
      <% @cheese.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cheeses/edit.html.erb
<h1>Editing cheese</h1>

<%= render 'form' %>

<%= link_to 'Show', @cheese %> |
<%= link_to 'Back', cheeses_path %>

app/views/cheeses/index.html.erb
<h1>Listing cheeses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cheeses.each do |cheese| %>
  <tr>
    <td><%= cheese.name %></td>
    <td><%= cheese.color %></td>
    <td><%= link_to 'Show', cheese %></td>
    <td><%= link_to 'Edit', edit_cheese_path(cheese) %></td>
    <td><%= link_to 'Destroy', cheese, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cheese', new_cheese_path %>

app/views/cheeses/new.html.erb
<h1>New cheese</h1>

<%= render 'form' %>

<%= link_to 'Back', cheeses_path %>

app/views/cheeses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @cheese.name %>
</p>

<p>
  <b>Color:</b>
  <%= @cheese.color %>
</p>


<%= link_to 'Edit', edit_cheese_path(@cheese) %> |
<%= link_to 'Back', cheeses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Found</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>